[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx prisma generate", "npx prisma migrate deploy", "next build"]

[start]
cmd = "npx prisma migrate deploy && npm start"
