[build]
builder = "DOCKERFILE"
buildCommand = ""

[deploy]
startCommand = "./scripts/start-production.sh"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
